### ISSUE TITLE
Question on the latest exercise set

### ISSUE THREAD

**Issue by ahmedgc** [tevgeniou/FoundationsML#7]
Hi, may I ask a question on the latest exercise set; specifically Exercise 1 Part 1...

In our lecture slides, we saw a special case of the bounded difference condition (for McDiarmid's Inequality):
$$ \sup_{z_1, \ldots, z_n, z_i'} | f(z_1, \ldots, z_n) - f(z_1,\ldots,z_{i-1}, z_i', z_{i+1}, \ldots, z_n) | \leq \frac{1}{n}  $$

Now, in the Exercise 1 Part 1 we're given that $\mathcal{H}$ is a class of $\\{-1,+1\\}$-valued functions over $\mathbb{R}^d$. But it seems to me that this fulfils a slightly different version of the bounded differences condition:
$$ \sup_{z_1, \ldots, z_n, z_i'} | f(z_1, \ldots, z_n) - f(z_1,\ldots,z_{i-1}, z_i', z_{i+1}, \ldots, z_n) | \leq \frac{\textbf{2}}{n}  $$

If I run with that, and apply the general form of McDiarmid (i.e. not from the lecture notes, but from, say, [Devroye et al](http://www.szit.bme.hu/~gyorfi/pbook.pdf) pp. 136), I end up with a slightly different version of the equality that we are meant to prove:
$$ \mathbb{E}_X \big(\hat{R}_n(\mathcal{H}, X) \big) \leq \hat{R}_n(\mathcal{H}, X) + \sqrt{\frac{\mathbf{2} \log(1/\delta)}{\mathbf{n}}}$$

So my question is: should we not have $\mathcal{H}$ as a class of $\\{\textbf{0},+1\\}$-valued functions, rather than $\\{\textbf{-1},+1\\}$-valued functions? 

BUT if that is indeed the case, it would have a knock-on effect on Exercise 1 Part 2, since the hint there relies on $\mathcal{H}$ being a class of $\\{-1,+1\\}$-valued functions for the property $\mathbb{I}\\{ y \ne h(x) \\} = (1 - yh(x))/2$... And there would of course be a knock-on effect on Exercise 1 Part 3 also!

Thanks,
Ahmed

**Comment by ahmedgc** [comment]
By the way, if anyone has issues viewing the Latex above, the [MathJax plugin for Chrome](https://chrome.google.com/webstore/detail/mathjax-plugin-for-github/ioemnmodlmafdkllaclgeombjnmnbima?hl=en) will render it legibly. (I don't know if there are similar plugins for other browsers.)

**Comment by sanghyunpark4** [comment]
I have the same issue.

**Comment by ahmedgc** [comment]
FYI, Prof. Vayatis has updated the exercise to take this into account:

[INSEAD-FML19-Exercises-S3.pdf](https://github.com/tevgeniou/FoundationsML/files/3145992/INSEAD-FML19-Exercises-S3.pdf)

I'll close this issue now.
